declare module 'express';
declare module 'morgan';
declare module 'jsonwebtoken';
declare module 'cors';
declare module 'cookie-parser';
declare module 'bcrypt';
declare module 'dotenv';
declare module 'mongoose-sequence';
declare module 'mongoose';
